version: 2

project_name: rust-app-sample
before:
  hooks:
    - sh -c 'echo "package main\n\nfunc main() {\n}" > dummy.go'

builds:
  - main: dummy.go
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    hooks:
      post:
        - ./build-cross-release.sh {{ .Os }} {{ .Arch }} {{ .Path }}

dockers:
  - image_templates:
    - ghcr.io/kounoike/{{ .ProjectName }}:latest-amd64
    - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Version }}-amd64
    - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Major }}-amd64
    - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64
    use: buildx
    goos: linux
    goarch: amd64
    skip_push: auto
  - image_templates:
    - ghcr.io/kounoike/{{ .ProjectName }}:latest-arm64
    - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Version }}-arm64
    - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Major }}-arm64
    - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64
    use: buildx
    goos: linux
    goarch: arm64
    skip_push: auto

docker_manifests:
  - name_template: ghcr.io/kounoike/{{ .ProjectName }}:latest
    image_templates:
      - ghcr.io/kounoike/{{ .ProjectName }}:latest-amd64
      - ghcr.io/kounoike/{{ .ProjectName }}:latest-arm64
    skip_push: auto
  - name_template: ghcr.io/kounoike/{{ .ProjectName }}:{{ .Version }}
    image_templates:
      - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Version }}-amd64
      - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Version }}-arm64
    skip_push: auto
  - name_template: ghcr.io/kounoike/{{ .ProjectName }}:{{ .Major }}
    image_templates:
      - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Major }}-amd64
      - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Major }}-arm64
    skip_push: auto
  - name_template: ghcr.io/kounoike/{{ .ProjectName }}:{{ .Major }}-{{ .Minor }}
    image_templates:
      - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-amd64
      - ghcr.io/kounoike/{{ .ProjectName }}:v{{ .Major }}.{{ .Minor }}-arm64
    skip_push: auto

release:
  github:
    owner: kounoike
    name: rust-app-sample
  replace_existing_draft: true
  replace_existing_artifacts: true
  prerelease: auto
  make_latest: true
  header: |
    ## Released v{{ .Version }} at {{ .Date }}
  footer: |
    Changelog is also available at [CHANGELOG.md](https://github.com/kounoike/rust-app-sample/blob/main/CHANGELOG.md)
  name_template: "🚀 {{ .ProjectName }} v{{ .Version }} "
