name: goreleaser

inputs:
  tag:
    description: 'The tag to release'
    required: true
  token:
    description: 'The GitHub token'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.token }}
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Install cross-rs
      uses: baptiste0928/cargo-install@v1
      with:
        crate: cross
    # - name: Set up Go
    #   uses: actions/setup-go@v5
    #   with:
    #     go-version: stable
    # More assembly might be required: Docker logins, GPG, etc.
    # It all depends on your needs.
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        # either 'goreleaser' (default) or 'goreleaser-pro'
        distribution: goreleaser
        # 'latest', 'nightly', or a semver
        version: "~> v2"
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        # Your GoReleaser Pro key, if you are using the 'goreleaser-pro' distribution
        # GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
