name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      # id-token: write
    steps:
      - uses: actions/checkout@v4
      - id: tagpr
        uses: Songmu/tagpr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/release
        with:
          tag: ${{ steps.tagpr.outputs.tag }}
        if: steps.tagpr.outputs.tag != ''
